### ISSUE TITLE
Solver return status solution

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/CentroidalPlanner#3]
This possibility is available only in the latest versions of ifopt:

[https://github.com/ethz-adrl/ifopt/blob/master/ifopt_core/include/ifopt/solver.h](https://github.com/ethz-adrl/ifopt/blob/master/ifopt_core/include/ifopt/solver.h)

while in the ROS Kinetic installation is not present. I would suggest to migrate to the new version locally (I mean to manually compile the latest version of ifopt) for people with Ubuntu 16.04 (like me) while the rest should have the right version (maybe someone with Ubuntu 18.04 and ROS whatever can confirm).

@FrancescoRuscelli @lucarossini-iit @alaurenzi @matteoparigi

**Comment by matteoparigi** [comment]
Yes, I confirm I have the latest version of ifopt (Ubuntu 18.04 + ROS melodic)

**Comment by EnricoMingo** [comment]
Ok so I will build locally the latest version so we have the new feature.

**Comment by EnricoMingo** [comment]
Done in last ```demo_cartesio_planner``` commit. I'll close.
